# Encoding: utf-8

task default: [:cop, :foodcritic, :spec]

desc 'Run ChefSpec unit tests'
task :spec do
  sh('rspec', '--format','documentation','test/unit')
end

desc 'Run RuboCop'
task :cop do
	sh('rubocop')
end

desc 'Run Foodcritic'
task :foodcritic do
	sh('foodcritic', '.')
end
