---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[fetch_json_data::default]
    attributes:
