# Encoding: utf-8

begin
  require 'rspec/core/rake_task'

  desc 'Run ChefSpec unit tests'
  RSpec::Core::RakeTask.new(:spec) do |t|
    t.rspec_opts = 'test/unit'
  end

  task default: :spec
rescue LoadError
  # no rspec available
end
